# Generated by Django 6.0.3 on 2026-03-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='cursos_inscritos', to='gestion.alumno'),
        ),
    ]
