# Generated by Django 6.0.3 on 2026-03-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Escuela Pro', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='escuela/')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Configuración de la Escuela',
                'verbose_name_plural': 'Configuración de la Escuela',
            },
        ),
    ]
