# Generated by Django 6.0.3 on 2026-03-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_curso_alumnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.CharField(default='Pendiente', max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='alumnos',
        ),
        migrations.AddField(
            model_name='alumno',
            name='cursos',
            field=models.ManyToManyField(related_name='alumnos', to='gestion.curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='archivo_temario',
            field=models.FileField(blank=True, null=True, upload_to='temarios/', verbose_name='Material de estudio / Temario'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
