# Generated by Django 6.0.3 on 2026-03-24 00:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_curso_profesor_remove_alumno_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('nota', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.curso')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'unique_together': {('alumno', 'curso')},
            },
        ),
        migrations.AlterField(
            model_name='alumno',
            name='cursos',
            field=models.ManyToManyField(related_name='alumnos', through='gestion.Inscripcion', to='gestion.curso'),
        ),
    ]
