# Generated by Django 6.0.3 on 2026-03-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_inscripcion_alter_alumno_cursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escuela', models.CharField(default='Mi Institución Educativa', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='escuela/')),
                ('eslogan', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Configuración de la Escuela',
                'verbose_name_plural': 'Configuración de la Escuela',
            },
        ),
    ]
